Add patches for CVEs 2022-34749 and 2020-15123
rapidsai/docker pull request #491
Opened 2022-08-17 22:51 UTC by msadang

{# Patch for CVE-2022-34749 https://github.com/advisories/GHSA-fw3v-x4f2-v673 #}
{# Patch for CVE-2020-15123 https://nvd.nist.gov/vuln/detail/CVE-2020-15123 #}

2022-08-17 23:12 UTC, raydouglass requested changes

2022-08-17 23:12 UTC, raydouglass commented on templates/rapidsai-core/partials/patch.dockerfile.j2
> +    && conda install mistune=2.0.3
Should make this >=2.0.3 to account for future versions.

2022-08-17 23:14 UTC, msadang commented on templates/rapidsai-core/partials/patch.dockerfile.j2
> +    && conda install mistune=2.0.3
Will make the change

2022-08-18 13:52 UTC, raydouglass commented on templates/rapidsai-core/partials/patch.dockerfile.j2
> +    && conda install mistune>=2.0.3
```suggestion
    && conda install "mistune>=2.0.3"
```

2022-08-18 17:12 UTC, raydouglass commented on templates/rapidsai-core/partials/patch.dockerfile.j2
> +    && conda install "mistune>=2.0.3"
```suggestion

RUN gpuci_mamba_retry install -y -n rapids "mistune>=2.0.3"
```
Should use mamba here instead. And run it outside of the `source activate rapids`.

2022-08-18 17:58 UTC, raydouglass commented on templates/rapidsai-core/partials/patch.dockerfile.j2
>      && npm i -g npm@">=7.0"
```suggestion
    && npm i -g npm@">=7.0" \
```
Need the trailing slash

2022-08-18 18:06 UTC, raydouglass approved these changes

2022-08-18 18:06 UTC, merged